In [1]:
import numpy as np
import pandas as pd

# Original NumPy array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print("Original NumPy array:")
print(arr)
print("Type:", type(arr))

# Convert NumPy array to Pandas DataFrame
df = pd.DataFrame(arr, columns=["Column1", "Column2", "Column3"])
print("\nNumPy array to a Pandas DataFrame:")
print(df)
print(type(df))

Original NumPy array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Type: <class 'numpy.ndarray'>

NumPy array to a Pandas DataFrame:
   Column1  Column2  Column3
0        1        2        3
1        4        5        6
2        7        8        9
<class 'pandas.core.frame.DataFrame'>
