In [1]:
import numpy as np

# Arrays
x = np.array([1, 2, 3])
y = np.array([[10], [20], [30]])

# Broadcasting addition
result = x + y

print("Result of element-wise addition with broadcasting:")
print(result)

Result of element-wise addition with broadcasting:
[[11 12 13]
 [21 22 23]
 [31 32 33]]
