In [1]:
import numpy as np

# Create a 1D array with 12 elements
arr = np.arange(12)
print("Original 1D array:")
print(arr)

# Reshape into 2D array of shape (3, 4)
reshaped = arr.reshape(3, 4)
print("\nReshaped 2D array (3x4):")
print(reshaped)

# Print strides
print("\nStrides of the reshaped array:")
print(reshaped.strides)

Original 1D array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped 2D array (3x4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Strides of the reshaped array:
(32, 8)
