## Multidimensional Array Slicer

In [7]:
import numpy as np 

def slice_third_dimension(arr):
    return arr[...,:2]

nums = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])

print(slice_third_dimension(nums))

[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]

 [[13 14]
  [16 17]]]
