In [1]:
import numpy as np

# Define vectors
x = np.array([1., 4., 0.])
y = np.array([2., 2., 1.])

print("Matrices and vectors.")
print("x:")
print(x)
print("y:")
print(y)

# Inner product
inner = np.inner(x, y)
print("\nInner product of x and y:")
print(inner)

# Outer product
outer = np.outer(x, y)
print("\nOuter product of x and y:")
print(outer)

# Cross product
cross = np.cross(x, y)
print("\nCross product of x and y:")
print(cross)

Matrices and vectors.
x:
[1. 4. 0.]
y:
[2. 2. 1.]

Inner product of x and y:
10.0

Outer product of x and y:
[[2. 2. 1.]
 [8. 8. 4.]
 [0. 0. 0.]]

Cross product of x and y:
[ 4. -1. -6.]
