In [1]:
import numpy as np
import pandas as pd

# Original NumPy array
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
print("Original NumPy Array:")
print(arr)

# Convert to DataFrame
df = pd.DataFrame(arr)

# Write to Excel file
excel_file = "array_to_excel.xlsx"
df.to_excel(excel_file, index=False, header=False)

# Read back from Excel file
df_loaded = pd.read_excel(excel_file, header=None)
arr_loaded = df_loaded.to_numpy()

print("\nLoaded NumPy Array from Excel File:")
print(arr_loaded)

Original NumPy Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Loaded NumPy Array from Excel File:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
