In [1]:
import numpy as np

# Create a reproducible random 3D array
np.random.seed(0)
arr = np.random.randint(0, 100, size=(3, 4, 5))
print("Original 3D array:\n", arr)

# Row and column indices for fancy indexing
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 3])

print("\nRow indices:")
print(row_indices)
print("Column indices:")
print(col_indices)

# Select elements: for each slice, pick given rows and columns
selected = arr[np.arange(arr.shape[0])[:, None], col_indices]

print("\nSelected elements:")
print(selected)

Original 3D array:
 [[[44 47 64 67 67]
  [ 9 83 21 36 87]
  [70 88 88 12 58]
  [65 39 87 46 88]]

 [[81 37 25 77 72]
  [ 9 20 80 69 79]
  [47 64 82 99 88]
  [49 29 19 19 14]]

 [[39 32 65  9 57]
  [32 31 74 23 35]
  [75 55 28 34  0]
  [ 0 36 53  5 38]]]

Row indices:
[0 1 2]
Column indices:
[1 2 3]

Selected elements:
[[[ 9 83 21 36 87]
  [70 88 88 12 58]
  [65 39 87 46 88]]

 [[ 9 20 80 69 79]
  [47 64 82 99 88]
  [49 29 19 19 14]]

 [[32 31 74 23 35]
  [75 55 28 34  0]
  [ 0 36 53  5 38]]]
