In [1]:
import numpy as np

# Example 1: 1D arrays
a = np.array([1, 2, 3])
b = np.array([0, 1, 0])
print("Original 1-d arrays:")
print(a)
print(b)

# Einstein summation convention (dot product here)
result1 = np.einsum('i,i', a, b)
print("Einstein’s summation convention of the said arrays:")
print(result1)


# Example 2: Higher dimension arrays
A = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
B = np.array([[ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])
print("\nOriginal Higher dimension:")
print(A)
print(B)

# Einstein summation convention (matrix multiplication here)
result2 = np.einsum('ij,jk->ik', A, B)
print("Einstein’s summation convention of the said arrays:")
print(result2)

Original 1-d arrays:
[1 2 3]
[0 1 0]
Einstein’s summation convention of the said arrays:
2

Original Higher dimension:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Einstein’s summation convention of the said arrays:
[[ 24  27  30]
 [ 78  90 102]
 [132 153 174]]
