In [1]:
import numpy as np

# Seed for reproducibility (so values match consistently)
np.random.seed(42)

# Create a 3x3x3 array with random values
arr = np.random.rand(3, 3, 3)

print("3x3x3 Array:\n", arr)

# Flatten to 1D array
flat_arr = arr.flatten()

print("\nFlattened 1D Array:\n", flat_arr)


3x3x3 Array:
 [[[0.37454012 0.95071431 0.73199394]
  [0.59865848 0.15601864 0.15599452]
  [0.05808361 0.86617615 0.60111501]]

 [[0.70807258 0.02058449 0.96990985]
  [0.83244264 0.21233911 0.18182497]
  [0.18340451 0.30424224 0.52475643]]

 [[0.43194502 0.29122914 0.61185289]
  [0.13949386 0.29214465 0.36636184]
  [0.45606998 0.78517596 0.19967378]]]

Flattened 1D Array:
 [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258 0.02058449 0.96990985
 0.83244264 0.21233911 0.18182497 0.18340451 0.30424224 0.52475643
 0.43194502 0.29122914 0.61185289 0.13949386 0.29214465 0.36636184
 0.45606998 0.78517596 0.19967378]
